apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubed-deployment
  labels:
    app: kubed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
    spec:
      containers:
      - name: kubed
        image: kubed:latest
        ports:
        - containerPort: 5001
